// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAHM6O0vTHMX5fHslm-MrP1ku0FfEGe5vg',
//     appId: '1:223163449165:web:e3c21030e1f73f73f68104',
//     messagingSenderId: '223163449165',
//     projectId: 'good-news-4fa69',
//     authDomain: 'good-news-4fa69.firebaseapp.com',
//     storageBucket: 'good-news-4fa69.firebasestorage.app',
//     measurementId: 'G-KXBE1XVF8D',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBj_omiftHzDsMdKlv3Ve5VISwCrIW8GCc',
//     appId: '1:223163449165:android:c922f2e0e19445e4f68104',
//     messagingSenderId: '223163449165',
//     projectId: 'good-news-4fa69',
//     storageBucket: 'good-news-4fa69.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBPmPxP-BHgiuE7mvylHo6zswePLnPCQXo',
//     appId: '1:223163449165:ios:7b44a7e38730430af68104',
//     messagingSenderId: '223163449165',
//     projectId: 'good-news-4fa69',
//     storageBucket: 'good-news-4fa69.firebasestorage.app',
//     iosBundleId: 'com.example.goodNews',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBPmPxP-BHgiuE7mvylHo6zswePLnPCQXo',
//     appId: '1:223163449165:ios:7b44a7e38730430af68104',
//     messagingSenderId: '223163449165',
//     projectId: 'good-news-4fa69',
//     storageBucket: 'good-news-4fa69.firebasestorage.app',
//     iosBundleId: 'com.example.goodNews',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAHM6O0vTHMX5fHslm-MrP1ku0FfEGe5vg',
//     appId: '1:223163449165:web:4e8e3d3438cfd5c6f68104',
//     messagingSenderId: '223163449165',
//     projectId: 'good-news-4fa69',
//     authDomain: 'good-news-4fa69.firebaseapp.com',
//     storageBucket: 'good-news-4fa69.firebasestorage.app',
//     measurementId: 'G-N2LEEVS30D',
//   );
// }
